
# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  packages: !include_dir_named packages

# GateMate Lab modular includes
input_boolean: !include helpers_input_boolean.yaml
input_number: !include helpers_input_number.yaml
template: !include binary_sensors.yaml

# Lovelace UI configuration updated to future proof dashboard
lovelace:
  dashboards:
    lovelace-yaml:
      mode: yaml
      filename: ui-lovelace.yaml
      title: GateMate
      icon: mdi:gate
      show_in_sidebar: true
      require_admin: false
    
    gatemate-diagnostics:
      mode: yaml
      filename: ui-diagnostics.yaml
      title: GateMate Diagnostics
      icon: mdi:flask
      show_in_sidebar: true
      require_admin: false

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
